import json
import os
import shutil
import tempfile
import unittest
from dataclasses import replace
from unittest import mock

from tests.test_agent_flow import BASE_CONFIG, make_agent
from wqb_agent.suggestion_workflow import SuggestionWorkflow


class TestSuggestionWorkflow(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.mkdtemp(prefix="wqb_suggestion_test_")

    def tearDown(self):
        shutil.rmtree(self._tmp, ignore_errors=True)

    def test_agent_facade_delegates_to_workflow(self):
        agent, _ = make_agent(self._tmp, rounds=1)
        expected = {"round_no": 3, "fields": []}
        with mock.patch.object(
            agent.suggestion_workflow, "run", return_value=expected
        ) as run:
            result = agent.run_suggestion_round(round_no=3)

        self.assertIs(result, expected)
        run.assert_called_once_with(round_no=3)

    def test_direct_workflow_matches_agent_facade_bundle(self):
        with tempfile.TemporaryDirectory(prefix="wqb_suggestion_direct_") as direct_tmp:
            facade_agent, _ = make_agent(self._tmp, rounds=1)
            direct_agent, _ = make_agent(direct_tmp, rounds=1)

            def discover(space, target_count):
                return [{
                    "id": "field_a",
                    "name": "Field A",
                    "description": "documented field",
                    "dataset": "pv1",
                    "type": "MATRIX",
                    "coverage": 0.9,
                    "frequency": "daily",
                    "alpha_count": 1,
                    "semantic_status": "KNOWN",
                }]

            facade_agent.discovery.discover = discover
            direct_agent.discovery.discover = discover
            facade_bundle = facade_agent.run_suggestion_round(round_no=1)
            direct_agent.refresh_operator_capability()
            direct_bundle = direct_agent.suggestion_workflow.run(round_no=1)
            with open(
                os.path.join(direct_tmp, "suggestions.json"), encoding="utf-8"
            ) as handle:
                persisted_bundle = json.load(handle)

        self.assertEqual(facade_bundle, direct_bundle)
        self.assertEqual(direct_bundle, persisted_bundle)
        self.assertEqual(
            set(direct_bundle),
            {
                "round_no", "epoch_label", "research_space", "fields", "context",
                "simulation_settings", "field_source", "operator_reference",
                "alpha_templates", "research_guard", "optimizer_context",
                "field_selection", "dataset_selection", "catalog_provenance",
            },
        )

    def test_fallback_preserves_call_order_and_target_counts(self):
        agent, _ = make_agent(self._tmp, rounds=1)
        calls = []

        def discover(space, target_count):
            calls.append((list(space["datasets"]), target_count))
            if len(calls) == 1:
                return []
            return [{
                "id": "cashflow_op",
                "name": "Operating cash flow",
                "description": "Operating cash flow generated by the business",
                "dataset": "fundamental6",
                "type": "MATRIX",
                "coverage": 0.9,
                "frequency": None,
                "alpha_count": 1,
                "semantic_status": "KNOWN",
                "field_source": agent.discovery.source_provenance(),
            }]

        agent.discovery.discover = discover
        bundle = agent.run_suggestion_round(round_no=1)

        self.assertEqual([target for _, target in calls], [6, 50])
        self.assertEqual(
            bundle["research_space"]["datasets"], ["fundamental6", "fundamental2"]
        )

    def test_suggestion_performs_no_simulation_or_checkpoint_write(self):
        agent, client = make_agent(self._tmp, rounds=1)
        checkpoint_write = mock.patch.object(
            agent.checkpoints, "write", wraps=agent.checkpoints.write
        )
        with checkpoint_write as write:
            agent.run_suggestion_round(round_no=1)

        self.assertEqual(client.sim_calls, [])
        self.assertEqual(write.call_count, 0)
        self.assertEqual(
            [name for name in os.listdir(self._tmp) if name.endswith(".checkpoint.json")],
            [],
        )
        with open(os.path.join(self._tmp, "suggestions.json"), encoding="utf-8") as handle:
            self.assertEqual(json.load(handle)["round_no"], 1)

    def test_trusted_parent_preserves_best_field_through_hook(self):
        agent, _ = make_agent(self._tmp, rounds=1)
        agent.suggestion_workflow.hooks = replace(
            agent.suggestion_workflow.hooks,
            form_research_space=lambda round_no: {
                "id": "parent-space",
                "statement": "test",
                "datasets": ["pv1"],
                "parent_best": "best-1",
            },
            trusted_current_best=lambda: {"id": "best-1"},
        )
        best_field = {
            "id": "best_field",
            "description": "field from trusted parent",
            "type": "MATRIX",
        }
        ensure_best_field = mock.Mock(return_value=[best_field])
        agent.suggestion_workflow.hooks = replace(
            agent.suggestion_workflow.hooks,
            ensure_best_field=ensure_best_field,
        )
        agent.discovery.discover = lambda space, target_count: []
        bundle = agent.run_suggestion_round(round_no=1)

        ensure_best_field.assert_called_once_with([])
        self.assertEqual(bundle["fields"][0]["id"], "best_field")

    def test_workflow_constructor_has_no_agent_or_transport_dependency(self):
        parameter_names = set(__import__("inspect").signature(SuggestionWorkflow).parameters)
        self.assertNotIn("agent", parameter_names)
        self.assertNotIn("client", parameter_names)

    def test_bundle_exposes_the_metric_aware_optimizer_context(self):
        agent, _ = make_agent(self._tmp, rounds=1)
        agent.discovery.discover = lambda space, target_count: []
        bundle = agent.run_suggestion_round(round_no=1)

        context = bundle["optimizer_context"]
        for key in (
            "eligible_parents", "failure_blocker_summary", "readiness_counts",
            "self_correlation_counts", "numeric_variants_available",
            "pre_correlation_eligibility", "generation_bound",
            "decision_contract", "blocked_reasons",
        ):
            self.assertIn(key, context)

    def test_optimizer_context_falls_back_to_the_gate_report(self):
        agent, _ = make_agent(self._tmp, rounds=1)
        workflow = agent.suggestion_workflow
        workflow.hooks = replace(workflow.hooks, optimizer_context=None)

        self.assertEqual(
            workflow._optimizer_context(), workflow.hooks.optimizer_gate_report()
        )


if __name__ == "__main__":
    unittest.main()
