"""Closed vocabulary for the quarantined legacy factory control plane."""

from __future__ import annotations

SESSION_STATUSES = frozenset({
    "RUNNING", "STOPPED", "RECONCILE_REQUIRED", "SIMULATION_BUDGET_CAP",
    "ROUND_CAP", "DEADLINE", "OPERATOR_CAPABILITY_BLOCKED",
})

SESSION_ACTIONS = frozenset({
    "START", "ADVANCE_ROUTE_EPISODE", "STOP_REQUESTED", "BLOCKER_COOLDOWN",
    "STOP_FEASIBILITY_BLOCKER", "STOP_PREFLIGHT_BLOCKER",
    "STOP_OPERATOR_CAPABILITY", "STOP_BUDGET_SHORTAGE",
    "INVALID_SIMULATION_QUOTA", "ZERO_DURATION", "WAIT_AGENT_DECISION",
    "STORAGE_RECONCILE_REQUIRED", "ORPHANED_PROPOSALS_BUDGET_BLOCKED",
    "RECOVER_PROPOSALS", "RECOVER_PROPOSALS_PENDING", "RECOVERED_PROPOSALS",
    "EXECUTION_RECONCILE_REQUIRED", "RECOVERY_BUDGET_BLOCKED",
    "RECOVER_CHECKPOINT", "CHECKPOINT_BLOCKED", "RECOVERED_CHECKPOINT",
    "ROUND_CAP", "BUDGET_BLOCKED", "SUGGEST", "WAIT_NO_SUGGESTION",
    "WAIT_INVALID_SUGGESTION", "FACTORY_BATCH_BUDGET_BLOCKED",
    "STOP_MECHANISM_ROUTE", "REROUTE_FACTORY_FEASIBILITY",
    "STOP_BUDGET_SHORTAGE", "REROUTE_BUDGET_SHORTAGE", "WAIT_FACTORY_BATCH",
    "PROPOSALS_WRITE_ERROR", "WAIT_NO_VALID_PROPOSAL", "RUN_PROPOSALS",
    "DAILY_OR_WEEKLY_BUDGET_BLOCKED", "RUN_PROPOSALS_PENDING",
    "WAIT_RUN_PROPOSALS", "ROUND_COMPLETE", "ASSEMBLE_ERROR",
    "RUN_PROPOSALS_ERROR", "RECOVER_PROPOSALS_ERROR",
    "RECOVER_CHECKPOINT_ERROR", "SUGGEST_ERROR",
    "ASSEMBLE_RECONCILE_REQUIRED", "RUN_PROPOSALS_RECONCILE_REQUIRED",
    "RECOVER_PROPOSALS_RECONCILE_REQUIRED",
    "RECOVER_CHECKPOINT_RECONCILE_REQUIRED",
    "SUGGEST_RECONCILE_REQUIRED",
})

RESULT_STATUSES = frozenset({
    "LOCAL_OWNER_BUSY", "RECONCILE_REQUIRED", "INVALID_SIMULATION_QUOTA",
    "INVALID_SESSION", "BLOCKED_RECHECK_NOT_DUE", "BLOCKER_UNCHANGED",
    "ORPHANED_PROPOSALS_BUDGET_BLOCKED", "RECOVERY_BUDGET_BLOCKED",
    "INVALID_RESEARCH_SPACE", "OPERATOR_CAPABILITY_UNKNOWN",
    "FACTORY_BATCH_BUDGET_BLOCKED", "FACTORY_FEASIBILITY_CHECK_BLOCKED",
    "FACTORY_BUDGET_SHORTAGE", "FACTORY_BATCH_NOT_READY",
    "DAILY_OR_WEEKLY_BUDGET_BLOCKED", "RUN_PROPOSALS_NOT_EXECUTED",
    "RETRYING", "ADVANCE_ROUTE_EPISODE",
})

BLOCKER_STOP_ACTIONS = {
    "FEASIBILITY": "STOP_FEASIBILITY_BLOCKER",
    "PREFLIGHT": "STOP_PREFLIGHT_BLOCKER",
    "OPERATOR_CAPABILITY": "STOP_OPERATOR_CAPABILITY",
    "BUDGET_SHORTAGE": "STOP_BUDGET_SHORTAGE",
}

TERMINAL_RECONCILE_ACTIONS = {
    "ASSEMBLE": "ASSEMBLE_RECONCILE_REQUIRED",
    "RUN_PROPOSALS": "RUN_PROPOSALS_RECONCILE_REQUIRED",
    "RECOVER_PROPOSALS": "RECOVER_PROPOSALS_RECONCILE_REQUIRED",
    "RECOVER_CHECKPOINT": "RECOVER_CHECKPOINT_RECONCILE_REQUIRED",
    "SUGGEST": "SUGGEST_RECONCILE_REQUIRED",
}

CONTROL_TOKENS = frozenset({
    "UNKNOWN", "NONE", "READY", "RUNNING", "STOPPED", "DEADLINE",
    "ROUND_CAP", "START", "ZERO_DURATION", "RECONCILE_REQUIRED",
    "INVALID_SESSION", "INVALID_SIMULATION_QUOTA", "RETRYING",
    "PREFLIGHT", "FEASIBILITY", "BUDGET_SHORTAGE", "OPERATOR_CAPABILITY",
    "PREFLIGHT_BLOCKED", "FACTORY_BATCH_BLOCKED", "FACTORY_BATCH_NOT_READY",
    "FACTORY_FEASIBILITY_CHECK_BLOCKED", "FACTORY_BUDGET_SHORTAGE",
    "RUN_PROPOSALS_NOT_EXECUTED", "BLOCKER_UNCHANGED", "BLOCKED_RECHECK_NOT_DUE",
    "SIMULATION_BUDGET_CAP", "OPERATOR_CAPABILITY_BLOCKED",
    "OPERATOR_CAPABILITY_UNKNOWN", "STOP_PREFLIGHT_BLOCKER",
    "FACTORY_BATCH_BUDGET_BLOCKED", "DAILY_OR_WEEKLY_BUDGET_BLOCKED",
    "ORPHANED_PROPOSALS_BUDGET_BLOCKED", "RECOVERY_BUDGET_BLOCKED",
    "BUDGET_BLOCKED", "STORAGE_RECONCILE_REQUIRED", "CHECKPOINT_BLOCKED",
    "EXECUTION_RECONCILE_REQUIRED", "STOP_REQUESTED", "WAIT_AGENT_DECISION",
    "WAIT_NO_SUGGESTION", "WAIT_INVALID_SUGGESTION", "WAIT_FACTORY_BATCH",
    "WAIT_NO_VALID_PROPOSAL", "WAIT_RUN_PROPOSALS", "RUN_PROPOSALS_PENDING",
    "RECOVER_PROPOSALS_PENDING", "RECOVER_CHECKPOINT", "RECOVERED_PROPOSALS",
    "RECOVERED_CHECKPOINT", "BLOCKER_COOLDOWN", "STOP_OPERATOR_CAPABILITY",
    "PROPOSALS_WRITE_ERROR", "ASSEMBLE_ERROR", "RUN_PROPOSALS_ERROR",
    "RECOVER_PROPOSALS_ERROR", "TARGETED_OPTIMIZATION_PENDING",
    "TARGETED_BATCH_INVALID", "TARGETED_BATCH_WRITTEN", "TARGETED_BATCH_REJECTED",
    "NO_TARGETED_PROPOSAL", "TARGETED_BATCH_UNCHANGED", "TARGETED_BATCH_CONFLICT",
    "TARGETED_BATCH_RECOVERY_BLOCKED", "ROUND_COMPLETE", "STOP_MECHANISM_ROUTE",
    "REROUTE_FACTORY_FEASIBILITY", "STOP_BUDGET_SHORTAGE", "REROUTE_BUDGET_SHORTAGE",
    "ADVANCE_ROUTE_EPISODE", "REROUTE", "STOP", "CANDIDATE_CHANGE_ONLY",
    "RESEARCH_INFORMATION_CHANGE", "CANDIDATE_CHANGE", "SEMANTIC_CHANGE",
    "RELATIONSHIP_CHANGE", "DATASET_CHANGE", "QUESTION_CHANGE", "FAILURE_TAXONOMY",
    "FREQUENCY_EVIDENCE", "CAPABILITY_STATUS", "BUDGET_SHORTAGE_REASON",
    "BUDGET_SHORTAGE_COUNT", "CURRENT_BUNDLE", "SAME_DATASET_RELATIONSHIP",
    "SAME_DATASET_NEW_MECHANISM", "NEW_DATASET_COMPOSITION", "REDISCOVERY",
    "FIELD_SEMANTICS_INSUFFICIENT", "FREQUENCY_EVIDENCE_INSUFFICIENT",
    "FREQUENCY_INCOMPATIBLE", "RELATIONSHIP_REVIEW", "MECHANISM_FAMILY_EXHAUSTED",
    "TEMPLATE_INCOMPATIBLE", "CROSS_DATASET_FEASIBILITY_ZERO", "PREFLIGHT_REJECTED",
    "DUPLICATE_LOCAL", "DIVERSITY_REJECTED", "INVALID_SETTINGS", "BATCH_CAP",
    "ALREADY_SIMULATED", "SUCCESS", "FAIL", "FAILED", "SUSPICIOUS_HIGH_SIGNAL",
    "PASS", "BLOCK",
}) | SESSION_STATUSES | SESSION_ACTIONS | RESULT_STATUSES | frozenset(
    BLOCKER_STOP_ACTIONS.values()
)
